### ISSUE TITLE
Add symlink to $PREFIX/share/rubygems/bin/ruby

### ISSUE THREAD

**Issue by wolfv** [conda-forge/ruby-feedstock#116] opened 2023-01-16 08:35 UTC
I've sucessfully installed `github_changelog_generator` as a gem, but then it complained about missing `share/rubygems/bin/ruby`:

```
(base) ➜  mamba git:(main) ✗ github_changelog_generator
/Users/wolfvollprecht/micromamba/share/rubygems/bin/github_changelog_generator: line 6: /Users/wolfvollprecht/micromamba/share/rubygems/bin/ruby: No such file or directory
/Users/wolfvollprecht/micromamba/share/rubygems/bin/github_changelog_generator: line 6: exec: /Users/wolfvollprecht/micromamba/share/rubygems/bin/ruby: cannot execute: No such file or directory
```

I was able to fix it by running:

```
ln -s ~/micromamba/bin/ruby /Users/wolfvollprecht/micromamba/share/rubygems/bin/ruby
```

**Comment by lmrodriguezr** [comment] 2023-07-27 11:59
I've created #122 which should solve this issue, but it's yet to be reviewed

**Comment by srstsavage** [comment] 2024-06-06 07:04
Hitting this as well. Thanks for putting together a fix, hopefully your PR will be merged eventually.

**Comment by sdruskat** [comment] 2024-06-27 16:48
> Hitting this as well. Thanks for putting together a fix, hopefully your PR will be merged eventually.

➕

**Comment by wolfv** [comment] 2024-06-27 16:54
I am looking at it! If someone wants to help get ruby 3.3.x out of the door, that would also be appreciated! :)

**Comment by sdruskat** [comment] 2024-06-28 07:14
> I am looking at it! If someone wants to help get ruby 3.3.x out of the door, that would also be appreciated! :)

Thanks! This is much appreciated! 🙏 

I'm afraid I'm personally not suited for helping with Ruby 3.3, as I'm new to conda and never touched Ruby (apart from using Jekyll and github-linguist). Sorry.

**Comment by wolfv** [comment] 2024-06-28 07:38
OK, I think I fixed everything. Also a 3.3.3 release is underway, but the symlink fix will be merged first. I still think there might be some simpler solution, but I need to look into the ruby(gems) source code to figure out if we can point it to another location.

**Closed** 2024-06-28 07:58 UTC

**Comment by sdruskat** [comment] 2024-08-03 16:54
I've just tried this, and it seems that the symlink was set incorrectly in `recipe/build.sh` in #122:

https://github.com/conda-forge/ruby-feedstock/blob/05d7453a068f542a4e198ff1c933ff4e23230851/recipe/build.sh#L46

It should be at `$PREFIX/share/rubygems/bin/ruby`.

I'm working on a PR (#130) that fixes this.

---

To reproduce the wrong symlink location, do, e.g.

```bash
mamba create -n gemtest
mamba activate gemtest
mamba install ruby
ls -la <PREFIX>/share/rubygems/  # ruby -> ../../bin/ruby*
```

To further test, try installing a gem and see it fail with the known error message, e.g.

```bash
mamba install compilers ruby libgit2=1.7.1 cmake pkg-config icu zlib
gem install github-linguist -- --use-system-libraries
which github-linguist  # <PREFIX>/share/rubygems/bin/github-linguist
github-linguist  # <PREFIX>/share/rubygems/bin/github-linguist: 6: exec: <PREFIX>/share/rubygems/bin/ruby: not found
```

**Comment by sdruskat** [comment] 2024-08-03 16:59
@wolfv (or other maintainers), please re-open this issue for the time being?

**Comment by iandol** [comment] 2024-10-30 00:45
Hi, I have been trying to work out why my Conda based Ruby tooling was constantly failing. I checked open issues, not suspecting in fact the problem was a closed issue that was not in fact fixed. This would have saved me over an hour of wasted time, please reopen.
